keys:
  - &desktop age17sk6tskwa38q7ced7r5fstn8wna3s4ee5mvzmjqfqrexwu00sctsuy0u8v
  - &mobile age1z26cecy0rvqcq3syz7dmjpxn6h7lhpvaufg8gut0k2v0rjpshfwq3sp8ga 
creation_rules:
  - path_regex: secret.yaml$
    key_groups:
    - age:
      - *desktop
      - *mobile
